name: Ubuntu
on: [workflow_dispatch]
jobs:
  build:
    #runs-on: ubuntu-18.04
    runs-on: ubuntu-latest
    #runs-on: ubuntu-20.04
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Checkout tools repo
        uses: actions/checkout@v4
        with:
          repository: HydrologicEngineeringCenter/dss-test-data
          path: dss-test-data

      - uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: build main library
        run: |
          cd heclib
          make

      - name: build and run basic C test programs
        run: |
          cd test/C
          ./unix_test

      - name: build and run Dss-C test program
        run: |
          cd test/Dss-C
          make test

      - name: build and run Fortran test program
        run: |
          cd test/Fortran
          make test

      - name: Run a one-line script
        run:  ls -l       #java -version

      # Save some artifacts
      - name: upload-artifacts hecdss.dll and javaHeclib.dll
        uses: actions/upload-artifact@v4
        with:
          name: dss
          path: |
             ${{ github.workspace }}/heclib/javaHeclib/Output/libjavaHeclib.so
             ${{ github.workspace }}/heclib/hecdss/libhecdss.so
           
